# Generated by Django 5.2.1 on 2025-05-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='bachelor',
            field=models.CharField(choices=[('administracion', 'Administración'), ('economia', 'Economía'), ('gobierno', 'Gobierno y Asuntos Públicos'), ('biologia', 'Biología'), ('fisica', 'Física'), ('geociencias', 'Geociencias'), ('matematicas', 'Matemáticas'), ('microbiologia', 'Microbiología'), ('quimica', 'Química'), ('medicina', 'Medicina'), ('arquitectura', 'Arquitectura'), ('arte', 'Arte'), ('diseno', 'Diseño'), ('historia_arte', 'Historia del Arte'), ('literatura', 'Literatura'), ('musica', 'Música'), ('narrativas', 'Narrativas Digitales'), ('ing_ambiental', 'Ingeniería Ambiental'), ('ing_biomedica', 'Ingeniería Biomédica'), ('ing_civil', 'Ingeniería Civil'), ('ing_electrica', 'Ingeniería Eléctrica'), ('ing_electronica', 'Ingeniería Electrónica'), ('ing_industrial', 'Ingeniería Industrial'), ('ing_mecanica', 'Ingeniería Mecánica'), ('ing_quimica', 'Ingeniería Química'), ('ing_alimentos', 'Ingeniería de Alimentos'), ('ing_sistemas', 'Ingeniería de Sistemas y Computación'), ('antropologia', 'Antropología'), ('ciencia_politica', 'Ciencia Política'), ('derecho', 'Derecho'), ('estudios_globales', 'Estudios Globales'), ('filosofia', 'Filosofía'), ('historia', 'Historia'), ('lenguas', 'Lenguas y Cultura'), ('psicologia', 'Psicología'), ('lic_artes', 'Lic. en Artes'), ('lic_biologia', 'Lic. en Biología'), ('lic_infantil', 'Lic. en Educación Infantil'), ('lic_espanol', 'Lic. en Español y Filología'), ('lic_filosofia', 'Lic. en Filosofía'), ('lic_fisica', 'Lic. en Física'), ('lic_historia', 'Lic. en Historia'), ('lic_matematicas', 'Lic. en Matemáticas'), ('lic_quimica', 'Lic. en Química'), ('estudios_dirigidos', 'Estudios Dirigidos')], default='', max_length=100),
        ),
    ]
