# Generated by Django 5.2 on 2025-05-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bachelor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='blocked_students',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='student',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_reviews',
        ),
    ]
