# Generated by Django 5.2.1 on 2025-05-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_bachelor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('subject_code', 'student'), name='unique_subject_per_student'),
        ),
    ]
