# Generated by Django 5.2.1 on 2025-05-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='blocked_students',
            field=models.ManyToManyField(blank=True, to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='friends',
            field=models.ManyToManyField(blank=True, to='contacts.contact'),
        ),
    ]
